Update init

diff --git a/init b/init
--- a/init
+++ b/init
@@ -292,36 +292,11 @@ fi
 echo "Setting DevTools docker environment"
 docker-machine active devtools || die "Command error"
 eval "$(docker-machine env devtools)" || die "Command error"
-#export DOCKER_HOST=$DOCKER_HOST
-#export DOCKER_TLS_VERIFY
-#export DOCKER_CERT_PATH
 
-#   No - Go to Docker install
-# Check if Docker >= 1.6 installed
-#   No - Go to Docker update
-# Check if Dockermachine 0.2 installed
-#   No - Go to Docker Machine install
-# Branch DevTools in GIT or use existing branch
-# Gather Git user name & Passworword
-# Verify Create Branch
-#   No - cancel
-# Create branch
-# Get dev volume path
-# Set DEVTOOLS_HOME
-# Create start script
-# Build DevTools container
-# Run start script - first run will install DevTools
+echo "Fetching devtools DockerFile and building initial devtools image"
+curl -L https://goo.gl/eJ9JYg > Dockerfile || die "Unable to fetch devtools Dockerfile"
+docker build -t devenv -t devtools . || die "Docker build failed"
+rm Dockerfile
 
-
-
-
-#cat >> $DEV_HOME/start <<-"EOL"
-#  #!/bin/bash
-#  echo $DEV_HOME
-#"EOL"
-
-#export PATH=$PATH:$DEV_HOME/bin
-
-#devtools info
-
-#devtools menu
+echo "Starting initial devtools container..."
+docker run -i -t devtools /bin/bash
