Working on init, updated .gitignore to omit bin and lib dirs

diff --git a/init b/init
--- a/init
+++ b/init
@@ -3,11 +3,19 @@
 PromptYN() {
   local resp
   while true; do
-    read -p "$1" resp
+    printf "$1"
+    read resp
     [ -z "$resp" ] && resp="$2"
     [[ "$resp" =~ ^[yY] ]] && return 0
     [[ "$resp" =~ ^[nN] ]] && return 1
   done
+}
+
+PromptString() {
+  unset resp
+  printf "$1"
+  read resp
+  [ -z "$resp" ] && resp="$2"
 }
 
 die() {
@@ -37,6 +45,103 @@ utility and Boot2Docker on Mac and Windows systems.
 
 EOL
 read -p "Press Enter to continue, or Ctrl-C to quit > "
+
+unset DEV_HOME
+echo
+echo "DEV_HOME"
+echo "Enter the base project directory on the local computer."
+echo "When working locally, this directory will be shared"
+echo "between the local system and your DevTools environment"
+while [ -z "$DEV_HOME" ]; do
+  PromptString "\nEnter DEV_HOME\n(Default $(pwd)) > " "$(pwd)"
+  cpath="$resp"
+  if [[ $cpath =~ ^\~(.*) ]]; then
+    cpath="${HOME}${BASH_REMATCH[1]}"
+  fi
+  oIFS=IFS; IFS="/"; din=($cpath); IFS=oIFS
+  if [ ${#din[@]} -lt 2 ] || [ -n "${din[0]}" ]; then
+    echo "Please specify an absolute path"
+    continue;
+  fi
+  p=0; ok=true; unset dout
+  for ((i=1; i<${#din[@]}; ++i)); do
+    el="${din[i]}"
+    case "$el" in
+      "" ) ;; # skip blank directory element
+      ".." ) # go to parent if not at root
+        if (( p < 1 )); then
+          echo "Invalid path specified"
+          ok=false
+          break
+        fi
+        (( p-- ))
+        ;;
+      "." ) ;; #ignore single dot
+      [a-zA-Z0-9_]* ) # at least one character
+        dout[$p]="$el"
+        (( ++p ))
+        ;;
+      * )
+        echo "Invalid path specified"
+        ok=false
+        break
+        ;;
+    esac
+  done
+  [ $ok == false ] && continue
+  unset cpath
+  for ((i=0; i<$p; ++i)); do
+    cpath="$cpath/${dout[i]}"
+  done
+  if [ -d "$cpath" ]
+    then
+    if PromptYN "Use existing directory $cpath? (Y/n) >" "Y"
+      then
+      DEV_HOME="$cpath"
+    else
+      continue
+    fi
+  else
+    if PromptYN "Create new directory $cpath? (Y/n) >" "Y"
+      then
+      if mkdir -p "$cpath"
+        then
+        DEV_HOME="$cpath"
+      else
+        echo "Unable to create directory: $cpath"
+      fi
+    fi
+  fi
+done
+[ -d "$DEV_HOME" ] || die "Failed to create $DEVTOOLS_HOME"
+cd "$DEV_HOME" || die "Command failed"
+export DEV_HOME
+export DEVTOOLS_HOME="$DEV_HOME/devtools"
+export DEVTOOLS_BIN="$DEVTOOLS_HOME/bin"
+export DEVTOOLS_LIB="$DEVTOOLS_HOME/lib"
+
+# setup DevTools bin & lib
+if [ ! -d "$DEVTOOLS_BIN" ]; then
+  echo "Creating $DEVTOOLS_BIN"
+  mkdir -p "$DEVTOOLS_BIN" || die "Command failed"
+fi
+if [ ! -d "$DEVTOOLS_LIB" ]; then
+  echo "Creating $DEVTOOLS_LIB"
+  mkdir -p "$DEVTOOLS_LIB" || die "Command failed"
+fi
+
+echo "Checking for local Node 0.12.2"
+if [ -d "$DEVTOOLS_LIB/node-v0.12.2-darwin-x64" ] && [ -f "$DEVTOOLS_LIB/node-v0.12.2-darwin-x64/bin/node" ]
+  then
+  echo "Detected: Node 0.12.2 in $DEVTOOLS_LIB/node-v0.12.2-darwin-x64"
+else
+  echo "Downloading and extracting local Node 0.12.2"
+  cd "$DEVTOOLS_LIB" || die "Command failed"
+  curl -L http://nodejs.org/dist/v0.12.2/node-v0.12.2-darwin-x64.tar.gz | gunzip | tar -x
+fi
+export DEVTOOLS_NODE="$DEVTOOLS_LIB/node-v0.12.2-darwin-x64/bin/node"
+export DEVTOOLS_NPM="$DEVTOOLS_LIB/node-v0.12.2-darwin-x64/bin/npm"
+cd "$DEV_HOME" || die "Command failed"
 
 # Check if docker-machine installed
 echo
